//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraL7Settings) DeepCopyInto(out *AviInfraL7Settings) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraL7Settings.
func (in *AviInfraL7Settings) DeepCopy() *AviInfraL7Settings {
	if in == nil {
		return nil
	}
	out := new(AviInfraL7Settings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraListeners) DeepCopyInto(out *AviInfraListeners) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.EnableSSL != nil {
		in, out := &in.EnableSSL, &out.EnableSSL
		*out = new(bool)
		**out = **in
	}
	if in.EnableHTTP2 != nil {
		in, out := &in.EnableHTTP2, &out.EnableHTTP2
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraListeners.
func (in *AviInfraListeners) DeepCopy() *AviInfraListeners {
	if in == nil {
		return nil
	}
	out := new(AviInfraListeners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraNSXSettings) DeepCopyInto(out *AviInfraNSXSettings) {
	*out = *in
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.T1LR != nil {
		in, out := &in.T1LR, &out.T1LR
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraNSXSettings.
func (in *AviInfraNSXSettings) DeepCopy() *AviInfraNSXSettings {
	if in == nil {
		return nil
	}
	out := new(AviInfraNSXSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSetting) DeepCopyInto(out *AviInfraSetting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Status = in.Status
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSetting.
func (in *AviInfraSetting) DeepCopy() *AviInfraSetting {
	if in == nil {
		return nil
	}
	out := new(AviInfraSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AviInfraSetting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingList) DeepCopyInto(out *AviInfraSettingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AviInfraSetting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingList.
func (in *AviInfraSettingList) DeepCopy() *AviInfraSettingList {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AviInfraSettingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingNetwork) DeepCopyInto(out *AviInfraSettingNetwork) {
	*out = *in
	if in.VipNetworks != nil {
		in, out := &in.VipNetworks, &out.VipNetworks
		*out = make([]AviInfraSettingVipNetwork, len(*in))
		copy(*out, *in)
	}
	if in.NodeNetworks != nil {
		in, out := &in.NodeNetworks, &out.NodeNetworks
		*out = make([]AviInfraSettingNodeNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableRhi != nil {
		in, out := &in.EnableRhi, &out.EnableRhi
		*out = new(bool)
		**out = **in
	}
	if in.EnablePublicIP != nil {
		in, out := &in.EnablePublicIP, &out.EnablePublicIP
		*out = new(bool)
		**out = **in
	}
	if in.BgpPeerLabels != nil {
		in, out := &in.BgpPeerLabels, &out.BgpPeerLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]AviInfraListeners, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingNetwork.
func (in *AviInfraSettingNetwork) DeepCopy() *AviInfraSettingNetwork {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingNodeNetwork) DeepCopyInto(out *AviInfraSettingNodeNetwork) {
	*out = *in
	if in.Cidrs != nil {
		in, out := &in.Cidrs, &out.Cidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingNodeNetwork.
func (in *AviInfraSettingNodeNetwork) DeepCopy() *AviInfraSettingNodeNetwork {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingNodeNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingSeGroup) DeepCopyInto(out *AviInfraSettingSeGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingSeGroup.
func (in *AviInfraSettingSeGroup) DeepCopy() *AviInfraSettingSeGroup {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingSeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingSpec) DeepCopyInto(out *AviInfraSettingSpec) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	out.SeGroup = in.SeGroup
	out.L7Settings = in.L7Settings
	in.NSXSettings.DeepCopyInto(&out.NSXSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingSpec.
func (in *AviInfraSettingSpec) DeepCopy() *AviInfraSettingSpec {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingStatus) DeepCopyInto(out *AviInfraSettingStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingStatus.
func (in *AviInfraSettingStatus) DeepCopy() *AviInfraSettingStatus {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviInfraSettingVipNetwork) DeepCopyInto(out *AviInfraSettingVipNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviInfraSettingVipNetwork.
func (in *AviInfraSettingVipNetwork) DeepCopy() *AviInfraSettingVipNetwork {
	if in == nil {
		return nil
	}
	out := new(AviInfraSettingVipNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullClientLogs) DeepCopyInto(out *FullClientLogs) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullClientLogs.
func (in *FullClientLogs) DeepCopy() *FullClientLogs {
	if in == nil {
		return nil
	}
	out := new(FullClientLogs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRule) DeepCopyInto(out *HTTPRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Status = in.Status
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRule.
func (in *HTTPRule) DeepCopy() *HTTPRule {
	if in == nil {
		return nil
	}
	out := new(HTTPRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRuleLBPolicy) DeepCopyInto(out *HTTPRuleLBPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRuleLBPolicy.
func (in *HTTPRuleLBPolicy) DeepCopy() *HTTPRuleLBPolicy {
	if in == nil {
		return nil
	}
	out := new(HTTPRuleLBPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRuleList) DeepCopyInto(out *HTTPRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRuleList.
func (in *HTTPRuleList) DeepCopy() *HTTPRuleList {
	if in == nil {
		return nil
	}
	out := new(HTTPRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRulePaths) DeepCopyInto(out *HTTPRulePaths) {
	*out = *in
	out.LoadBalancerPolicy = in.LoadBalancerPolicy
	out.TLS = in.TLS
	if in.HealthMonitors != nil {
		in, out := &in.HealthMonitors, &out.HealthMonitors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRulePaths.
func (in *HTTPRulePaths) DeepCopy() *HTTPRulePaths {
	if in == nil {
		return nil
	}
	out := new(HTTPRulePaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRuleSpec) DeepCopyInto(out *HTTPRuleSpec) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]HTTPRulePaths, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRuleSpec.
func (in *HTTPRuleSpec) DeepCopy() *HTTPRuleSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRuleStatus) DeepCopyInto(out *HTTPRuleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRuleStatus.
func (in *HTTPRuleStatus) DeepCopy() *HTTPRuleStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRuleTLS) DeepCopyInto(out *HTTPRuleTLS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRuleTLS.
func (in *HTTPRuleTLS) DeepCopy() *HTTPRuleTLS {
	if in == nil {
		return nil
	}
	out := new(HTTPRuleTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRule) DeepCopyInto(out *HostRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Status = in.Status
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRule.
func (in *HostRule) DeepCopy() *HostRule {
	if in == nil {
		return nil
	}
	out := new(HostRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleAnalyticsPolicy) DeepCopyInto(out *HostRuleAnalyticsPolicy) {
	*out = *in
	if in.FullClientLogs != nil {
		in, out := &in.FullClientLogs, &out.FullClientLogs
		*out = new(FullClientLogs)
		(*in).DeepCopyInto(*out)
	}
	if in.LogAllHeaders != nil {
		in, out := &in.LogAllHeaders, &out.LogAllHeaders
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleAnalyticsPolicy.
func (in *HostRuleAnalyticsPolicy) DeepCopy() *HostRuleAnalyticsPolicy {
	if in == nil {
		return nil
	}
	out := new(HostRuleAnalyticsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleGSLB) DeepCopyInto(out *HostRuleGSLB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleGSLB.
func (in *HostRuleGSLB) DeepCopy() *HostRuleGSLB {
	if in == nil {
		return nil
	}
	out := new(HostRuleGSLB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleHTTPPolicy) DeepCopyInto(out *HostRuleHTTPPolicy) {
	*out = *in
	if in.PolicySets != nil {
		in, out := &in.PolicySets, &out.PolicySets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleHTTPPolicy.
func (in *HostRuleHTTPPolicy) DeepCopy() *HostRuleHTTPPolicy {
	if in == nil {
		return nil
	}
	out := new(HostRuleHTTPPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleList) DeepCopyInto(out *HostRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleList.
func (in *HostRuleList) DeepCopy() *HostRuleList {
	if in == nil {
		return nil
	}
	out := new(HostRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleSSLKeyCertificate) DeepCopyInto(out *HostRuleSSLKeyCertificate) {
	*out = *in
	out.AlternateCertificate = in.AlternateCertificate
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleSSLKeyCertificate.
func (in *HostRuleSSLKeyCertificate) DeepCopy() *HostRuleSSLKeyCertificate {
	if in == nil {
		return nil
	}
	out := new(HostRuleSSLKeyCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleSecret) DeepCopyInto(out *HostRuleSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleSecret.
func (in *HostRuleSecret) DeepCopy() *HostRuleSecret {
	if in == nil {
		return nil
	}
	out := new(HostRuleSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleSpec) DeepCopyInto(out *HostRuleSpec) {
	*out = *in
	in.VirtualHost.DeepCopyInto(&out.VirtualHost)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleSpec.
func (in *HostRuleSpec) DeepCopy() *HostRuleSpec {
	if in == nil {
		return nil
	}
	out := new(HostRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleStatus) DeepCopyInto(out *HostRuleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleStatus.
func (in *HostRuleStatus) DeepCopy() *HostRuleStatus {
	if in == nil {
		return nil
	}
	out := new(HostRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleTCPListeners) DeepCopyInto(out *HostRuleTCPListeners) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleTCPListeners.
func (in *HostRuleTCPListeners) DeepCopy() *HostRuleTCPListeners {
	if in == nil {
		return nil
	}
	out := new(HostRuleTCPListeners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleTCPSettings) DeepCopyInto(out *HostRuleTCPSettings) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]HostRuleTCPListeners, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleTCPSettings.
func (in *HostRuleTCPSettings) DeepCopy() *HostRuleTCPSettings {
	if in == nil {
		return nil
	}
	out := new(HostRuleTCPSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleTLS) DeepCopyInto(out *HostRuleTLS) {
	*out = *in
	out.SSLKeyCertificate = in.SSLKeyCertificate
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleTLS.
func (in *HostRuleTLS) DeepCopy() *HostRuleTLS {
	if in == nil {
		return nil
	}
	out := new(HostRuleTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostRuleVirtualHost) DeepCopyInto(out *HostRuleVirtualHost) {
	*out = *in
	if in.Datascripts != nil {
		in, out := &in.Datascripts, &out.Datascripts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableVirtualHost != nil {
		in, out := &in.EnableVirtualHost, &out.EnableVirtualHost
		*out = new(bool)
		**out = **in
	}
	in.HTTPPolicy.DeepCopyInto(&out.HTTPPolicy)
	out.Gslb = in.Gslb
	out.TLS = in.TLS
	if in.AnalyticsPolicy != nil {
		in, out := &in.AnalyticsPolicy, &out.AnalyticsPolicy
		*out = new(HostRuleAnalyticsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPSettings != nil {
		in, out := &in.TCPSettings, &out.TCPSettings
		*out = new(HostRuleTCPSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ICAPProfile != nil {
		in, out := &in.ICAPProfile, &out.ICAPProfile
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRuleVirtualHost.
func (in *HostRuleVirtualHost) DeepCopy() *HostRuleVirtualHost {
	if in == nil {
		return nil
	}
	out := new(HostRuleVirtualHost)
	in.DeepCopyInto(out)
	return out
}
