/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1alpha1"
	scheme "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/client/v1alpha1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HealthMonitorsGetter has a method to return a HealthMonitorInterface.
// A group's client should implement this interface.
type HealthMonitorsGetter interface {
	HealthMonitors(namespace string) HealthMonitorInterface
}

// HealthMonitorInterface has methods to work with HealthMonitor resources.
type HealthMonitorInterface interface {
	Create(ctx context.Context, healthMonitor *v1alpha1.HealthMonitor, opts v1.CreateOptions) (*v1alpha1.HealthMonitor, error)
	Update(ctx context.Context, healthMonitor *v1alpha1.HealthMonitor, opts v1.UpdateOptions) (*v1alpha1.HealthMonitor, error)
	UpdateStatus(ctx context.Context, healthMonitor *v1alpha1.HealthMonitor, opts v1.UpdateOptions) (*v1alpha1.HealthMonitor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HealthMonitor, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HealthMonitorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HealthMonitor, err error)
	HealthMonitorExpansion
}

// healthMonitors implements HealthMonitorInterface
type healthMonitors struct {
	client rest.Interface
	ns     string
}

// newHealthMonitors returns a HealthMonitors
func newHealthMonitors(c *AkoV1alpha1Client, namespace string) *healthMonitors {
	return &healthMonitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the healthMonitor, and returns the corresponding healthMonitor object, and an error if there is any.
func (c *healthMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HealthMonitor, err error) {
	result = &v1alpha1.HealthMonitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("healthmonitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HealthMonitors that match those selectors.
func (c *healthMonitors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HealthMonitorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HealthMonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("healthmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested healthMonitors.
func (c *healthMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("healthmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a healthMonitor and creates it.  Returns the server's representation of the healthMonitor, and an error, if there is any.
func (c *healthMonitors) Create(ctx context.Context, healthMonitor *v1alpha1.HealthMonitor, opts v1.CreateOptions) (result *v1alpha1.HealthMonitor, err error) {
	result = &v1alpha1.HealthMonitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("healthmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(healthMonitor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a healthMonitor and updates it. Returns the server's representation of the healthMonitor, and an error, if there is any.
func (c *healthMonitors) Update(ctx context.Context, healthMonitor *v1alpha1.HealthMonitor, opts v1.UpdateOptions) (result *v1alpha1.HealthMonitor, err error) {
	result = &v1alpha1.HealthMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("healthmonitors").
		Name(healthMonitor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(healthMonitor).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *healthMonitors) UpdateStatus(ctx context.Context, healthMonitor *v1alpha1.HealthMonitor, opts v1.UpdateOptions) (result *v1alpha1.HealthMonitor, err error) {
	result = &v1alpha1.HealthMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("healthmonitors").
		Name(healthMonitor.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(healthMonitor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the healthMonitor and deletes it. Returns an error if one occurs.
func (c *healthMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("healthmonitors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *healthMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("healthmonitors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched healthMonitor.
func (c *healthMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HealthMonitor, err error) {
	result = &v1alpha1.HealthMonitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("healthmonitors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
