FROM golang:latest AS build
ENV BUILD_PATH="gitlab.eng.vmware.com/orion/akc/"
RUN mkdir -p $GOPATH/src/$BUILD_PATH

COPY . $GOPATH/src/$BUILD_PATH
WORKDIR $GOPATH/src/$BUILD_PATH

RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -o $GOPATH/bin/akc -mod=vendor $BUILD_PATH/cmd/akc-main

FROM alpine:latest
COPY --from=build /go/bin/akc .
ENTRYPOINT ["./akc"]

