apiVersion: ako.vmware.com/v1alpha1
kind: HealthMonitor
metadata:
  labels:
    app.kubernetes.io/name: ako-crd-operator
    app.kubernetes.io/managed-by: kustomize
  name: healthmonitor-sample
spec:
  # TODO(user): Add fields here
