/*
 * Copyright © 2025 Broadcom Inc. and/or its subsidiaries. All Rights Reserved.
 * All Rights Reserved.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*   http://www.apache.org/licenses/LICENSE-2.0
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

// @AI-Generated
// This test file was generated by Claude AI assistant.
package lib

import (
	"strings"
	"testing"
	"unicode"
)

// TestGenerateSecurePassword verifies that generated passwords meet Avi Controller policy requirements
func TestGenerateSecurePassword(t *testing.T) {
	password, err := generateSecurePassword()
	if err != nil {
		t.Fatalf("generateSecurePassword() failed: %v", err)
	}

	// Verify password meets all requirements
	if err := validatePasswordPolicy(password); err != nil {
		t.Errorf("Password validation failed: %v\nPassword: %s", err, password)
	}
}

// TestRandomCharFromSet verifies random character selection
func TestRandomCharFromSet(t *testing.T) {
	tests := []struct {
		name    string
		charset string
		wantErr bool
	}{
		{
			name:    "lowercase characters",
			charset: "abcdefghijklmnopqrstuvwxyz",
			wantErr: false,
		},
		{
			name:    "uppercase characters",
			charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
			wantErr: false,
		},
		{
			name:    "digits",
			charset: "0123456789",
			wantErr: false,
		},
		{
			name:    "special characters",
			charset: "!@#$%^&*()~",
			wantErr: false,
		},
		{
			name:    "single character",
			charset: "a",
			wantErr: false,
		},
		{
			name:    "empty charset",
			charset: "",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			char, err := randomCharFromSet(tt.charset)
			if (err != nil) != tt.wantErr {
				t.Errorf("randomCharFromSet() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !tt.wantErr {
				if !strings.ContainsRune(tt.charset, rune(char)) {
					t.Errorf("randomCharFromSet() returned char '%c' not in charset '%s'", char, tt.charset)
				}
			}
		})
	}
}

// validatePasswordPolicy checks if a password meets Avi Controller requirements
// Requirements: minimum 10 characters with at least 1 uppercase, 1 lowercase, 1 numeric, 1 special
func validatePasswordPolicy(password string) error {
	const (
		minLength       = 10
		allowedSpecials = "!@#$%^&*()~"
	)

	// Check minimum length
	if len(password) < minLength {
		return &ValidationError{
			Field:   "password",
			Message: "password must be at least 10 characters",
		}
	}

	// Count character types
	hasLowercase := false
	hasUppercase := false
	hasDigit := false
	hasSpecial := false

	for _, char := range password {
		if unicode.IsLower(char) {
			hasLowercase = true
		}
		if unicode.IsUpper(char) {
			hasUppercase = true
		}
		if unicode.IsDigit(char) {
			hasDigit = true
		}
		if strings.ContainsRune(allowedSpecials, char) {
			hasSpecial = true
		}

		// Check for invalid characters
		if !unicode.IsLetter(char) && !unicode.IsDigit(char) && !strings.ContainsRune(allowedSpecials, char) {
			return &ValidationError{
				Field:   "password",
				Message: "password contains invalid character: " + string(char),
			}
		}
	}

	// Verify all required character types are present
	if !hasLowercase {
		return &ValidationError{
			Field:   "password",
			Message: "password must contain at least 1 lowercase character",
		}
	}
	if !hasUppercase {
		return &ValidationError{
			Field:   "password",
			Message: "password must contain at least 1 uppercase character",
		}
	}
	if !hasDigit {
		return &ValidationError{
			Field:   "password",
			Message: "password must contain at least 1 numeric character",
		}
	}
	if !hasSpecial {
		return &ValidationError{
			Field:   "password",
			Message: "password must contain at least 1 special character",
		}
	}

	return nil
}

// ValidationError represents a password validation error
type ValidationError struct {
	Field   string
	Message string
}

func (e *ValidationError) Error() string {
	return e.Message
}
