/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1alpha2"
	akov1alpha2 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/client/v1alpha2/clientset/versioned/typed/ako/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeL4Rules implements L4RuleInterface
type fakeL4Rules struct {
	*gentype.FakeClientWithList[*v1alpha2.L4Rule, *v1alpha2.L4RuleList]
	Fake *FakeAkoV1alpha2
}

func newFakeL4Rules(fake *FakeAkoV1alpha2, namespace string) akov1alpha2.L4RuleInterface {
	return &fakeL4Rules{
		gentype.NewFakeClientWithList[*v1alpha2.L4Rule, *v1alpha2.L4RuleList](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("l4rules"),
			v1alpha2.SchemeGroupVersion.WithKind("L4Rule"),
			func() *v1alpha2.L4Rule { return &v1alpha2.L4Rule{} },
			func() *v1alpha2.L4RuleList { return &v1alpha2.L4RuleList{} },
			func(dst, src *v1alpha2.L4RuleList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.L4RuleList) []*v1alpha2.L4Rule { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha2.L4RuleList, items []*v1alpha2.L4Rule) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
