/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSSLProfiles implements SSLProfileInterface
type FakeSSLProfiles struct {
	Fake *FakeAkoV1alpha1
	ns   string
}

var sslprofilesResource = v1alpha1.SchemeGroupVersion.WithResource("sslprofiles")

var sslprofilesKind = v1alpha1.SchemeGroupVersion.WithKind("SSLProfile")

// Get takes name of the sSLProfile, and returns the corresponding sSLProfile object, and an error if there is any.
func (c *FakeSSLProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SSLProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sslprofilesResource, c.ns, name), &v1alpha1.SSLProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSLProfile), err
}

// List takes label and field selectors, and returns the list of SSLProfiles that match those selectors.
func (c *FakeSSLProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SSLProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sslprofilesResource, sslprofilesKind, c.ns, opts), &v1alpha1.SSLProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SSLProfileList{ListMeta: obj.(*v1alpha1.SSLProfileList).ListMeta}
	for _, item := range obj.(*v1alpha1.SSLProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sSLProfiles.
func (c *FakeSSLProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sslprofilesResource, c.ns, opts))

}

// Create takes the representation of a sSLProfile and creates it.  Returns the server's representation of the sSLProfile, and an error, if there is any.
func (c *FakeSSLProfiles) Create(ctx context.Context, sSLProfile *v1alpha1.SSLProfile, opts v1.CreateOptions) (result *v1alpha1.SSLProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sslprofilesResource, c.ns, sSLProfile), &v1alpha1.SSLProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSLProfile), err
}

// Update takes the representation of a sSLProfile and updates it. Returns the server's representation of the sSLProfile, and an error, if there is any.
func (c *FakeSSLProfiles) Update(ctx context.Context, sSLProfile *v1alpha1.SSLProfile, opts v1.UpdateOptions) (result *v1alpha1.SSLProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sslprofilesResource, c.ns, sSLProfile), &v1alpha1.SSLProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSLProfile), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSSLProfiles) UpdateStatus(ctx context.Context, sSLProfile *v1alpha1.SSLProfile, opts v1.UpdateOptions) (*v1alpha1.SSLProfile, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sslprofilesResource, "status", c.ns, sSLProfile), &v1alpha1.SSLProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSLProfile), err
}

// Delete takes name of the sSLProfile and deletes it. Returns an error if one occurs.
func (c *FakeSSLProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(sslprofilesResource, c.ns, name, opts), &v1alpha1.SSLProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSSLProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sslprofilesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SSLProfileList{})
	return err
}

// Patch applies the patch and returns the patched sSLProfile.
func (c *FakeSSLProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SSLProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sslprofilesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SSLProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSLProfile), err
}
