/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePKIProfiles implements PKIProfileInterface
type FakePKIProfiles struct {
	Fake *FakeAkoV1alpha1
	ns   string
}

var pkiprofilesResource = v1alpha1.SchemeGroupVersion.WithResource("pkiprofiles")

var pkiprofilesKind = v1alpha1.SchemeGroupVersion.WithKind("PKIProfile")

// Get takes name of the pKIProfile, and returns the corresponding pKIProfile object, and an error if there is any.
func (c *FakePKIProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PKIProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pkiprofilesResource, c.ns, name), &v1alpha1.PKIProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PKIProfile), err
}

// List takes label and field selectors, and returns the list of PKIProfiles that match those selectors.
func (c *FakePKIProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PKIProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pkiprofilesResource, pkiprofilesKind, c.ns, opts), &v1alpha1.PKIProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PKIProfileList{ListMeta: obj.(*v1alpha1.PKIProfileList).ListMeta}
	for _, item := range obj.(*v1alpha1.PKIProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pKIProfiles.
func (c *FakePKIProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pkiprofilesResource, c.ns, opts))

}

// Create takes the representation of a pKIProfile and creates it.  Returns the server's representation of the pKIProfile, and an error, if there is any.
func (c *FakePKIProfiles) Create(ctx context.Context, pKIProfile *v1alpha1.PKIProfile, opts v1.CreateOptions) (result *v1alpha1.PKIProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pkiprofilesResource, c.ns, pKIProfile), &v1alpha1.PKIProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PKIProfile), err
}

// Update takes the representation of a pKIProfile and updates it. Returns the server's representation of the pKIProfile, and an error, if there is any.
func (c *FakePKIProfiles) Update(ctx context.Context, pKIProfile *v1alpha1.PKIProfile, opts v1.UpdateOptions) (result *v1alpha1.PKIProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pkiprofilesResource, c.ns, pKIProfile), &v1alpha1.PKIProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PKIProfile), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePKIProfiles) UpdateStatus(ctx context.Context, pKIProfile *v1alpha1.PKIProfile, opts v1.UpdateOptions) (*v1alpha1.PKIProfile, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pkiprofilesResource, "status", c.ns, pKIProfile), &v1alpha1.PKIProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PKIProfile), err
}

// Delete takes name of the pKIProfile and deletes it. Returns an error if one occurs.
func (c *FakePKIProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(pkiprofilesResource, c.ns, name, opts), &v1alpha1.PKIProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePKIProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pkiprofilesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PKIProfileList{})
	return err
}

// Patch applies the patch and returns the patched pKIProfile.
func (c *FakePKIProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PKIProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pkiprofilesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PKIProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PKIProfile), err
}
