/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	akov1beta1 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HTTPRuleLister helps list HTTPRules.
// All objects returned here must be treated as read-only.
type HTTPRuleLister interface {
	// List lists all HTTPRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*akov1beta1.HTTPRule, err error)
	// HTTPRules returns an object that can list and get HTTPRules.
	HTTPRules(namespace string) HTTPRuleNamespaceLister
	HTTPRuleListerExpansion
}

// hTTPRuleLister implements the HTTPRuleLister interface.
type hTTPRuleLister struct {
	listers.ResourceIndexer[*akov1beta1.HTTPRule]
}

// NewHTTPRuleLister returns a new HTTPRuleLister.
func NewHTTPRuleLister(indexer cache.Indexer) HTTPRuleLister {
	return &hTTPRuleLister{listers.New[*akov1beta1.HTTPRule](indexer, akov1beta1.Resource("httprule"))}
}

// HTTPRules returns an object that can list and get HTTPRules.
func (s *hTTPRuleLister) HTTPRules(namespace string) HTTPRuleNamespaceLister {
	return hTTPRuleNamespaceLister{listers.NewNamespaced[*akov1beta1.HTTPRule](s.ResourceIndexer, namespace)}
}

// HTTPRuleNamespaceLister helps list and get HTTPRules.
// All objects returned here must be treated as read-only.
type HTTPRuleNamespaceLister interface {
	// List lists all HTTPRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*akov1beta1.HTTPRule, err error)
	// Get retrieves the HTTPRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*akov1beta1.HTTPRule, error)
	HTTPRuleNamespaceListerExpansion
}

// hTTPRuleNamespaceLister implements the HTTPRuleNamespaceLister
// interface.
type hTTPRuleNamespaceLister struct {
	listers.ResourceIndexer[*akov1beta1.HTTPRule]
}
