{{- if .Values.VKSSettings.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ako-vks-cr
  labels:
    app.kubernetes.io/name: ako
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: vks-integration
rules:
  # Cluster API Resources - Required for cluster watching and labeling
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "update", "patch"]
  
  # Cluster API Status - Required for cluster phase monitoring
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["clusters/status"]
    verbs: ["get", "list", "watch"]
  
  # VKS Add-on Framework - AddonInstall management
  - apiGroups: ["addons.kubernetes.vmware.com"]
    resources: ["addoninstalls"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # VKS Add-on Framework - AddonInstall status monitoring
  - apiGroups: ["addons.kubernetes.vmware.com"]
    resources: ["addoninstalls/status"]
    verbs: ["get", "list", "watch"]
  
  # VMCI Proxy Integration - ManagementService CRDs (read-only)
  # These CRDs are exposed by vCenter in supervisor cluster via govmomi/vmodl
  - apiGroups: ["vmware.com"]
    resources: ["managementservices"]
    verbs: ["get", "list", "watch"]
  
  # VMCI Proxy Integration - ManagementServiceAccessGrant CRDs (read-only)
  # These CRDs are exposed by vCenter in supervisor cluster via govmomi/vmodl
  - apiGroups: ["vmware.com"]
    resources: ["managementserviceaccessgrants"]
    verbs: ["get", "list", "watch"]
  
  # Namespace Operations - Required for SEG detection
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  
  # Events - Required for VKS operation logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  
  # ConfigMaps and Secrets - Required for dependency resource management (Tasks 2.1, 2.2)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

{{- end }} 