{{- if .Values.AKOSettings.primaryInstance }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass" }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: avi-lb
  {{ if eq .Values.L7Settings.defaultIngController "true" }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{ end }}
spec:
  controller: ako.vmware.com/avi-lb
{{ end }}
{{- end }}