{{- if and .Values.avicredentials.username (or .Values.avicredentials.password .Values.avicredentials.authtoken) -}}
apiVersion: v1
kind: Secret
metadata:
  name: avi-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ako.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.avicredentials.username | b64enc }}
  {{ if .Values.avicredentials.password  }}
  password: {{ .Values.avicredentials.password | b64enc }}
  {{ end }}
  {{ if .Values.avicredentials.authtoken  }}
  authtoken: {{ .Values.avicredentials.authtoken | b64enc }}
  {{ end }}
  {{ if .Values.avicredentials.certificateAuthorityData  }}
  certificateAuthorityData: {{ .Values.avicredentials.certificateAuthorityData | b64enc }}
  {{ end }}
{{- end -}}