# This rule is not used by the project ako-crd-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ako.vmware.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ako-crd-operator
    app.kubernetes.io/managed-by: kustomize
  name: applicationprofile-admin-role
rules:
- apiGroups:
  - ako.vmware.com
  resources:
  - applicationprofiles
  verbs:
  - '*'
- apiGroups:
  - ako.vmware.com
  resources:
  - applicationprofiles/status
  verbs:
  - get
