/*
 * Copyright © 2025 Broadcom Inc. and/or its subsidiaries. All Rights Reserved.
 * All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// @AI-Generated
// [Generated by Cursor claude-4-sonnet]
//
// This file contains unit tests for DeleteAviObjects function in ako_init.go.
// Only tests that actually increase code coverage are included.

package miscellaneous

import (
	"testing"

	avicache "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/cache"
	"github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/k8s"
)

// ========================================
// DeleteAviObjects Tests
// ========================================

// Note: DeleteAviObjects calls rest.NewRestOperations which requires AVI controller setup.
// These tests verify the function logic without triggering actual REST operations.

func TestDeleteAviObjects_EmptyKeys(t *testing.T) {
	// Test with empty keys - should not panic
	aviObjCache := avicache.NewAviObjCache()
	parentVSKeys := []avicache.NamespaceName{}

	// Actually call the function with empty keys - should not panic
	k8s.DeleteAviObjects(parentVSKeys, aviObjCache)

	t.Log("DeleteAviObjects with empty keys completed without panic")
}

func TestDeleteAviObjects_NonExistentVS(t *testing.T) {
	// Test with non-existent VS
	aviObjCache := avicache.NewAviObjCache()

	vsKey := avicache.NamespaceName{Namespace: "admin", Name: "non-existent-vs"}
	parentVSKeys := []avicache.NamespaceName{vsKey}

	// Verify VS doesn't exist in cache
	_, found := aviObjCache.VsCacheMeta.AviCacheGet(vsKey)
	if found {
		t.Error("VS should not exist in cache")
	}

	// Call function - should handle non-existent VS gracefully
	k8s.DeleteAviObjects(parentVSKeys, aviObjCache)

	t.Log("DeleteAviObjects handled non-existent VS successfully")
}

func TestDeleteAviObjects_WrongCacheType(t *testing.T) {
	// Test with wrong cache type
	aviObjCache := avicache.NewAviObjCache()

	vsKey := avicache.NamespaceName{Namespace: "admin", Name: "vs1"}
	aviObjCache.VsCacheMeta.AviCacheAdd(vsKey, "wrong-type")
	parentVSKeys := []avicache.NamespaceName{vsKey}

	// Verify wrong type is in cache
	obj, found := aviObjCache.VsCacheMeta.AviCacheGet(vsKey)
	if !found {
		t.Error("Object should be in cache")
	}

	// Verify type assertion would fail
	_, ok := obj.(*avicache.AviVsCache)
	if ok {
		t.Error("Type assertion should fail for wrong type")
	}

	// Call function - should handle wrong type gracefully
	k8s.DeleteAviObjects(parentVSKeys, aviObjCache)

	t.Log("DeleteAviObjects handled wrong cache type successfully")
}
