/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostRules implements HostRuleInterface
type FakeHostRules struct {
	Fake *FakeAkoV1beta1
	ns   string
}

var hostrulesResource = v1beta1.SchemeGroupVersion.WithResource("hostrules")

var hostrulesKind = v1beta1.SchemeGroupVersion.WithKind("HostRule")

// Get takes name of the hostRule, and returns the corresponding hostRule object, and an error if there is any.
func (c *FakeHostRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.HostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostrulesResource, c.ns, name), &v1beta1.HostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostRule), err
}

// List takes label and field selectors, and returns the list of HostRules that match those selectors.
func (c *FakeHostRules) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.HostRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostrulesResource, hostrulesKind, c.ns, opts), &v1beta1.HostRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HostRuleList{ListMeta: obj.(*v1beta1.HostRuleList).ListMeta}
	for _, item := range obj.(*v1beta1.HostRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostRules.
func (c *FakeHostRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostrulesResource, c.ns, opts))

}

// Create takes the representation of a hostRule and creates it.  Returns the server's representation of the hostRule, and an error, if there is any.
func (c *FakeHostRules) Create(ctx context.Context, hostRule *v1beta1.HostRule, opts v1.CreateOptions) (result *v1beta1.HostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostrulesResource, c.ns, hostRule), &v1beta1.HostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostRule), err
}

// Update takes the representation of a hostRule and updates it. Returns the server's representation of the hostRule, and an error, if there is any.
func (c *FakeHostRules) Update(ctx context.Context, hostRule *v1beta1.HostRule, opts v1.UpdateOptions) (result *v1beta1.HostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostrulesResource, c.ns, hostRule), &v1beta1.HostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHostRules) UpdateStatus(ctx context.Context, hostRule *v1beta1.HostRule, opts v1.UpdateOptions) (*v1beta1.HostRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hostrulesResource, "status", c.ns, hostRule), &v1beta1.HostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostRule), err
}

// Delete takes name of the hostRule and deletes it. Returns an error if one occurs.
func (c *FakeHostRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hostrulesResource, c.ns, name, opts), &v1beta1.HostRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.HostRuleList{})
	return err
}

// Patch applies the patch and returns the patched hostRule.
func (c *FakeHostRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostrulesResource, c.ns, name, pt, data, subresources...), &v1beta1.HostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostRule), err
}
